# `np.sort()`

In [1]:
import numpy as np
a = np.random.randint(1,100,15)
a


array([23, 53, 87, 85, 44,  6, 20, 64, 10, 35,  8, 67,  3, 30, 69])

In [7]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[76, 10, 80, 79],
       [23,  7, 69,  7],
       [95, 20, 22, 19],
       [21, 22, 75, 46],
       [15, 70,  7,  1],
       [73,  8, 38, 68]])

In [8]:
e = np.unique([11,2,2,2,33,3,33,11])
np.unique(e)

array([ 2,  3, 11, 33])

In [10]:
a

array([23, 53, 87, 85, 44,  6, 20, 64, 10, 35,  8, 67,  3, 30, 69])

# `.np.expand_dims()`

In [12]:
v = np.expand_dims(a, axis=0)
v

array([[23, 53, 87, 85, 44,  6, 20, 64, 10, 35,  8, 67,  3, 30, 69]])

In [14]:
print(a.ndim)
print()
print(v.ndim)

1

2


In [17]:
y = np.expand_dims(a, axis = 1)
print(a.ndim)
print()
print(y.ndim)

1

2


# `.np.where()`
finds all indices...

In [18]:
np.where(a>50)

(array([ 1,  2,  3,  7, 11, 14]),)

In [20]:
c = a[a>50]
c

array([53, 87, 85, 64, 67, 69])

### Replace all values > 50 with...

In [21]:
np.where(a>50,0,a)

array([23,  0,  0,  0, 44,  6, 20,  0, 10, 35,  8,  0,  3, 30,  0])

### Replace all even numbers from zero

In [23]:
print(a)
print()
np.where(a%2==0,0,a)

[23 53 87 85 44  6 20 64 10 35  8 67  3 30 69]



array([23, 53, 87, 85,  0,  0,  0,  0,  0, 35,  0, 67,  3,  0, 69])

In [25]:
print(a)
print()
np.where(a%2!=0,0,a)

[23 53 87 85 44  6 20 64 10 35  8 67  3 30 69]



array([ 0,  0,  0,  0, 44,  6, 20, 64, 10,  0,  8,  0,  0, 30,  0])

# `np.argmax()`

In [27]:
a

array([23, 53, 87, 85, 44,  6, 20, 64, 10, 35,  8, 67,  3, 30, 69])

In [29]:
print("value ", np.max(a))
print()
print("index ", np.argmax(a))

value  87

index  2


In [30]:
print(b)
print()
print(np.max(b))
print()
print(np.argmax(b))

[[76 10 80 79]
 [23  7 69  7]
 [95 20 22 19]
 [21 22 75 46]
 [15 70  7  1]
 [73  8 38 68]]

95

8


# Column-wise

In [31]:
np.argmax(b,axis=0)

array([2, 4, 0, 0])

# Row-wise

In [32]:
np.argmax(b,axis=1)

array([2, 2, 0, 2, 1, 0])

# `np.argmin()`

In [33]:
print(a)
print("value ", np.min(a))
print()
print("index ", np.argmin(a))

[23 53 87 85 44  6 20 64 10 35  8 67  3 30 69]
value  3

index  12


# `np.cumsum()`

In [35]:
print(a)
print()
print(np.cumsum(a))

[23 53 87 85 44  6 20 64 10 35  8 67  3 30 69]

[ 23  76 163 248 292 298 318 382 392 427 435 502 505 535 604]


In [36]:
print(b)
print()
print(np.cumsum(b))

[[76 10 80 79]
 [23  7 69  7]
 [95 20 22 19]
 [21 22 75 46]
 [15 70  7  1]
 [73  8 38 68]]

[ 76  86 166 245 268 275 344 351 446 466 488 507 528 550 625 671 686 756
 763 764 837 845 883 951]


In [37]:
print(b)
print()
print(np.cumsum(b,axis=0))

[[76 10 80 79]
 [23  7 69  7]
 [95 20 22 19]
 [21 22 75 46]
 [15 70  7  1]
 [73  8 38 68]]

[[ 76  10  80  79]
 [ 99  17 149  86]
 [194  37 171 105]
 [215  59 246 151]
 [230 129 253 152]
 [303 137 291 220]]


## percentile stuff...

In [38]:
print(a)
print()
print(np.percentile(a,100))

[23 53 87 85 44  6 20 64 10 35  8 67  3 30 69]

87.0


In [39]:
print(np.percentile(a,50))

35.0


In [41]:
np.median(a)

35.0

# <p style = "text-align: center;">`np.flip()`</p>

In [43]:
a

array([23, 53, 87, 85, 44,  6, 20, 64, 10, 35,  8, 67,  3, 30, 69])

In [45]:
np.flip(a)

array([69, 30,  3, 67,  8, 35, 10, 64, 20,  6, 44, 85, 87, 53, 23])

In [47]:
b

array([[76, 10, 80, 79],
       [23,  7, 69,  7],
       [95, 20, 22, 19],
       [21, 22, 75, 46],
       [15, 70,  7,  1],
       [73,  8, 38, 68]])

In [48]:
np.flip(b)

array([[68, 38,  8, 73],
       [ 1,  7, 70, 15],
       [46, 75, 22, 21],
       [19, 22, 20, 95],
       [ 7, 69,  7, 23],
       [79, 80, 10, 76]])

# Column-flipping

In [50]:
print(b)
print()
np.flip(b,axis=0)

[[76 10 80 79]
 [23  7 69  7]
 [95 20 22 19]
 [21 22 75 46]
 [15 70  7  1]
 [73  8 38 68]]



array([[73,  8, 38, 68],
       [15, 70,  7,  1],
       [21, 22, 75, 46],
       [95, 20, 22, 19],
       [23,  7, 69,  7],
       [76, 10, 80, 79]])

# `np.put()`

In [52]:
a

array([23, 53, 87, 85, 44,  6, 20, 64, 10, 35,  8, 67,  3, 30, 69])

### _first give the array then index after._

In [55]:
np.put(a,[0,1], [110,530])
a

array([110, 530,  87,  85,  44,   6,  20,  64,  10,  35,   8,  67,   3,
        30,  69])

# <p style = "text-align: center;"> `np.delete()`</p>

In [56]:
a

array([110, 530,  87,  85,  44,   6,  20,  64,  10,  35,   8,  67,   3,
        30,  69])

### _delete first item_

In [58]:
np.delete(a,0)

array([530,  87,  85,  44,   6,  20,  64,  10,  35,   8,  67,   3,  30,
        69])

In [59]:
np.delete(a,[0,4,3])

array([530,  87,   6,  20,  64,  10,  35,   8,  67,   3,  30,  69])

# <p style = "text-align: center;">`np.clip()`</p>


In [61]:
a

array([110, 530,  87,  85,  44,   6,  20,  64,  10,  35,   8,  67,   3,
        30,  69])

In [62]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 75, 75, 44, 25, 25, 64, 25, 35, 25, 67, 25, 30, 69])